version: "3.9"

services:
  service-db:
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres -h service-db", "--quiet" ]
      interval: 1s
      timeout: 5s
      retries: 9
    container_name: db_spend_easy
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: db_spend_easy
    ports:
      - "5432:5432"
    volumes:
      - postgres:/var/lib/postgres/data
    networks:
      - spend_easy_net

  spring-boot-app:
    container_name: spend_easy_app
    image: spend_easy
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8085:8085"
    networks:
      - spend_easy_net
    depends_on:
      service-db:
        condition: service_healthy

  pgadmin:
    container_name: pgadmin4_container
    image: dpage/pgadmin4:7
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    volumes:
      - pgadmin-data:/var/lib/pgadmin

volumes:
  postgres:
  pgadmin-data:

networks:
  spend_easy_net:
    driver: bridge