### Register user
POST http://localhost:8080/api/v1/auth/register
Content-Type: application/json

{
  "name": "Valera",
  "email": "valera@valera.com",
  "password": "valera",
  "role": "ADMIN"
}

> {% client.global.set("auth-token", response.body.access_token) %}

### Test Demo
GET http://localhost:8080/api/v1/demo
Authorization: Bearer {{auth-token}}


### Change the password
PATCH http://localhost:8080/api/v1/users
Content-Type: application/json
Authorization: Bearer {{auth-token}}

{
  "currentPassword": "valera",
  "newPassword": "password",
  "confirmationPassword": "password"
}


### Auth user with new password
POST http://localhost:8080/api/v1/auth/login
Content-Type: application/json

{
  "email": "valera@valera.com",
  "password": "password"
}

> {% client.global.set("new-auth-token", response.body.access_token) %}


### Test Demo after password change
GET http://localhost:8080/api/v1/demo
Authorization: Bearer {{new-auth-token}}