name: Build $ Deploy Spend Easy app

on:
  push:
    - main

jobs:
  build-deploy:
    name: Build & Deploy app
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'corretto'
          java-version: 17

      - name: Unit tests
        run: mvn -B test --file pom.xml

      - name: Build the app
        run:
          mvn clean
          mvn -B package --file pom.xml